[tool.poetry]
name = "papis-extract"
version = "0.1.0"
description = ""
authors = ["Marty Oehme <marty.oehme@gmail.com>"]
readme = "README.md"
packages = [{include = "papis_extract"}]

[tool.poetry.dependencies]
python = "^3.11"
pymupdf = "^1.23.1"
levenshtein = "^0.21.1"
papis = "^0.13"
click = "^8.1.7"
whoosh = "^2.7.4"
python-magic = "^0.4.27"

[tool.poetry.plugins."papis.command"]
extract = "papis_extract:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
