steps:
  lint_ruff:
    image: ghcr.io/astral-sh/uv:python3.11-trixie-slim
    commands:
      - uv tool install ruff
      - python --version && uv --version && ruff --version
      - echo "----------------- running ruff lint ------------------"
      - ruff check .

  format_ruff:
    image: ghcr.io/astral-sh/uv:python3.11-trixie-slim
    commands:
      - uv tool install ruff
      - python --version && uv --version && ruff --version
      - echo "----------------- running ruff format ------------------"
      - ruff format --check .
