steps:
  pyright:
    image: nikolaik/python-nodejs
    commands:
      - npm install --global pyright
      - poetry install
      - python --version && poetry --version && pyright --version
      - echo "------------- running pyright typecheck -------------"
      - poetry run pyright
