steps:
  pyright:
    image: nikolaik/python-nodejs
    commands:
      - npm install --global pyright
      - uv sync
      - python --version && uv version && pyright --version
      - echo "------------- running pyright typecheck -------------"
      - uv run pyright
