steps:
  pyright:
    image: ghcr.io/astral-sh/uv:python3.11-trixie-slim
    commands:
      - uv tool install pyright
      - uv sync --locked
      - python --version && uv --version && pyright --version
      - echo "------------- running pyright typecheck -------------"
      - uv run pyright
