when:
  branch: main

steps:
  pytest:
    image: nikolaik/python-nodejs
    commands:
      - uv sync
      - python --version && uv version
      - echo "------------- running pytest -------------"
      - uv run pytest
