when:
  - event: push

steps:
  pytest:
    image: ghcr.io/astral-sh/uv:python3.11-trixie-slim
    commands:
      - uv sync --locked
      - python --version && uv --version
      - echo "------------- running pytest -------------"
      - uv run pytest
